# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: default

steps:
- task: JFrogGenericArtifacts@1
  inputs:
    command: 'Upload'
    connection: 'artifactory-test'
    specSource: 'taskConfiguration'
    fileSpec: |
      {
        "files": [
          {
            "pattern": "*.sh",
            "target": "global-generic-local"
          }
        ]
      }
    failNoOp: true
- task: JFrogPublishBuildInfo@1
  inputs:
    artifactoryConnection: 'artifactory-test'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'