#!/bin/bash
#set -x
#####################################
#creator: Daniel Poterman
#date: 27/02/19
#version: 0.0.1
#####################################

#this scripts will show your network interface, mac address and ip address in a chart.
if [ -f /sbin/ifconfig ] ;
    then echo "ifconfig exists" ;
    fi

divider=========================================
divider=$divider$divider

##format strings for printf
header="\n %-10s %11s  %10s\n"
format="%-10s %10s %10s\n"

#width of divider
totalwidth=44

#print categories
printf "$header" INTERFACE IP MAC

#print divider to match width of report
printf "%$totalwidth.${totalwidth}s\n" "$divider"

interface=$(ifconfig |cut -f1 |grep -v "lo" |awk '{print $1}' |egrep 'enp|wlp') \
ip=$(ifconfig |egrep 'inet'|grep -v inet6|awk '{print $2}') \
mac=$(ifconfig |egrep 'ether'|grep -v inet6|awk '{print $2}')  


#print lines of report
printf "$format" $interface $ip $mac


